version: '3.3'

services:
  jenkins:
#    image: jenkins/jenkins:lts-jdk11
    image: jenkins-zedek:latest
    container_name: jenkins
    restart: unless-stopped
    
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
    
    ports:
      - 8080:8080
      - 50000:50000
    
    networks:
      - jenkins_net

 
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    
    ports:
      - "9000:9000"
    
    networks:
      - jenkins_net

  db:
    image: postgres:12
    
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    
    networks:
      - jenkins_net

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

networks:
  jenkins_net:
    driver: bridge
